### ISSUE TITLE
Fatal error during activation

### ISSUE THREAD

**Issue by OpenDog** [awslabs/amazon-polly-wordpress-plugin#10]
This is happening with 1.0.11

> Fatal error: Can't use function return value in write context in /home4/xxxxx/public_html/wp-content/plugins/amazon-polly/admin/class-amazonpolly-admin.php on line 560

Am I doing something wrong?

**Comment by tstachlewski** [comment]
Hi!
I'm pretty sure that the problem is connected with PHP version which you are using. The plugin requires PHP 5.6 (https://wordpress.org/plugins/amazon-polly/)

**Comment by OpenDog** [comment]
Ah. My bad. You are totally right.
