### ISSUE TITLE
Ability to exclude some posts from RSS feed, but still make a narration for them

### ISSUE THREAD

**Issue by neilc314** [awslabs/amazon-polly-wordpress-plugin#12]
I have some posts for which I would like to create narrations, but not publicize to services such as iTunes through the auto-generated RSS feed. In the post edit page, there should be an option to exclude a post from being added to the pollycast RSS feed.

**Comment by tstachlewski** [comment]
Would it be OK, to specify 'category' of posts which would be added to feed (and nothing else)?

**Comment by neilc314** [comment]
Yes, that would work in my case.

**Comment by tstachlewski** [comment]
Hi,
I have added possibility to specify category(categories) of posts, which will be added to RSS feed in version 2.0.4.

Cheers,
