### ISSUE TITLE
PHP Error with Bridge premium theme v. 16.6 when publishing a post

### ISSUE THREAD

**Issue by StephaneTurquay** [awslabs/amazon-polly-wordpress-plugin#14]
Hi,

I'm running a blog with Bridge premium theme v16.6 and Amazon Polly WP Plugin v. 2.0.2. I get the below PHP Error every time I publish or update a blog post:

```
Warning: Cannot modify header information - headers already sent by (output started at .../wp-includes/functions.php:1476) in .../wp-admin/post.php on line 198

Warning: Cannot modify header information - headers already sent by (output started at .../wp-includes/functions.php:1476) in .../wp-includes/pluggable.php on line 1216
```

Even thought this error is thrown, the post is published or updated and the content is generated properly through Polly and player displayed on the blog post.

When I disable the plugin I don't have the error anymore so there is something between the theme and the plugin.

Thanks for your help!

**Comment by tstachlewski** [comment]
Hi, Thanks for you help! The fix will be provided in next release.

**Comment by StephaneTurquay** [comment]
Super! Thank you Tomasz!!
