### ISSUE TITLE
Need to include channel author information in the "by" field

### ISSUE THREAD

**Issue by Carlo-Carandang** [awslabs/amazon-polly-wordpress-plugin#17]
In the Amazon Polly WordPress plugin code, the channel author "by" field has the input for the channel title of the podcast, as illustrated in the following code, lines 64 to 67, path amazon-polly-wordpress-plugin/includes/template-amazon-pollycast.php:

```
<itunes:owner>
    <itunes:name><?php wp_title_rss(); ?></itunes:name>
    <itunes:email><?php echo $amazon_pollycast->get_itunes_email(); ?></itunes:email>
</itunes:owner>
```

Instead of inserting the channel title wp_title_rss() for <itunes:name>, please replace with the channel author name, such as wp_author_rss(). Currently, the channel title and author is: wp_title_rss() by wp_title_rss(). Please change to wp_title_rss() by wp_author_rss(). Thanks.

Current snapshot of my feed, which outputs the following Channel Title by Author "Depression Boss by Depression Boss":

![image](https://user-images.githubusercontent.com/30868659/45489038-8f4ce400-b739-11e8-8d45-c66f0799a6bf.png)

Current snapshot of podcast in iTunes:

![image](https://user-images.githubusercontent.com/30868659/45489295-4a757d00-b73a-11e8-9dbb-ece8dae2afdc.png)

**Comment by tstachlewski** [comment]
Hi,
Will be fixed in next release. Probably this week.
Cheers

**Comment by Carlo-Carandang** [comment]
Thanks!

**Comment by tstachlewski** [comment]
Hi. I have added possibility to specify author in plugin configuration in latest plugin version (2.5.5)

**Comment by Carlo-Carandang** [comment]
Thanks for your prompt response.

**Comment by Carlo-Carandang** [comment]
Still no author name in the "by" field:
![image](https://user-images.githubusercontent.com/30868659/45593151-87698b80-b955-11e8-878f-d020ef65fcef.png)

Is it the line <itunes:author></itunes:author> that needs to change?
```
<channel>
	<title>Depression Boss</title>
	<atom:link href="https://depressionboss.com/feed/amazon-pollycast/" rel="self" type="application/rss+xml" />
	<link>https://depressionboss.com</link>
	<description>Effectively Treating Depression</description>
	<image>
		<url>http://depressionboss.com/wp-content/uploads/2018/08/cropped-logo_db-9.png</url>
		<title>Depression Boss</title>
		<link>https://depressionboss.com</link>
	</image>
	<itunes:owner>
		<itunes:name>Carlo Carandang</itunes:name>
		<itunes:email>carandangc@gmail.com</itunes:email>
	</itunes:owner>
	<itunes:category text="Health"></itunes:category>
	<itunes:explicit>no</itunes:explicit>
	<itunes:image href="http://depressionboss.com/wp-content/uploads/2018/08/cropped-logo_db-9.png"/>
	<itunes:author>Depression Boss</itunes:author>
	<itunes:summary>Effectively Treating Depression</itunes:summary>
	<itunes:subtitle>Effectively Treating Depression</itunes:subtitle>
	<copyright>Copyright © 2018 Depression Boss</copyright>
	<lastBuildDate>
	Thu, 13 Sep 2018 16:10:36 +0000	</lastBuildDate>
	<!--<pubDate>Fri, 18 May 2012 00:00:00 EST</pubDate>-->
	<language>en-US</language>
	<sy:updatePeriod>
	hourly	</sy:updatePeriod>
	<sy:updateFrequency>
```

**Comment by tstachlewski** [comment]
Hi,
I've changed the one in <itunes:owner>, but I see that there is the second (the one which you have mentioned). It will be fixed in next release.

Cheers,
Tomasz

**Comment by Carlo-Carandang** [comment]
Fixed...thanks for the prompt bug fix!
