### ISSUE TITLE
Add a hook to for a proper label

### ISSUE THREAD

**Issue by richtabor** [awslabs/amazon-polly-wordpress-plugin#4]
Hey all! I'm loving the plugin — it's just great! 👏👏

What do you think about adding a hook just before the player's markup? That way a label could be properly added so visitors know exactly what they'll be listening to when you click "play".

Below is a screenshot of what I implemented on my [WordPress development & design blog](https://richtabor.com/gutenberg-thoughts/), though it was a bit overkill filtering the_content based on the before or after post visibility.

<img width="1022" alt="screeny" src="https://user-images.githubusercontent.com/1813435/36699702-7aaa5902-1b1b-11e8-9bd7-96502875f047.png">

We wouldn't need the actual label, like I added, simply a hook to assign markup to.

So what do you think?

**Comment by tstachlewski** [comment]
Hi!
This was great idea, so we have added it to the plugin! :) Thanks for it!

**Comment by richtabor** [comment]
Awesome! Good stuff mate!
