### ISSUE TITLE
p tags with align attribute are stripped

### ISSUE THREAD

**Issue by ravichandrach1** [awslabs/amazon-polly-wordpress-plugin#9]
Version 1.0.7 added the `amazon_polly_allowed_tags_tinymce` function which adds ssml tags to the tinyMCE `extended_valid_elements`. The `p` tag is added with no attribute specified, this is overriding the default WordPress `p` tag with `align` attribute and tinyMCE is stripping `p` tags with any attribute.

Steps to reproduce:
1. Add/Edit a post
2. Switch to the "Text" tab and insert the below HTML
`<p align="center">Center aligned text</p>`
`<p align="left">left aligned text</p>`
3. Switch to "Visual" tab and switch back to "Text" tab, the `p` tags would be stripped now

**Comment by tstachlewski** [comment]
Thx ravichandrach1 ! I will update/fix it next week. Thx for info!

**Comment by tstachlewski** [comment]
Fixed in 1.0.11
